version: '3.8'

services:
  web:
    build: .
    container_name: restapi_faceverif
    command: gunicorn restapi_faceverif.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
